include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - unnecessary_const
